const fakeDB = [
  {
    id: "coldSnacks",
    title: "ХОЛОДНЫЕ ЗАКУСКИ",
    data: [
      {
        id: 1,
        image: "item-1.png",
        title: "Ягненок",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "620 ₽",
      },
      {
        id: 2,
        image: "item-2.png",
        title: "Индейка",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "450 ₽",
      },
      {
        id: 3,
        image: "item-3.png",
        title: "Гусь",
        weight: "Вес: 225 г",
        description: "Фаршированный яблоками",
        price: "7 900 ₽",
      },
      {
        id: 4,
        image: "item-4.png",
        title: "Утка",
        weight: "Вес: 225 г",
        description: "Фаршированная рисом, курагой и айвой",
        price: "3 230 ₽",
      },
      {
        id: 5,
        image: "item-1.png",
        title: "Ягненок",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "620 ₽",
      },
      {
        id: 6,
        image: "item-2.png",
        title: "Индейка",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "450 ₽",
      },
    ],
  },
  {
    id: "hotSnacks",
    title: "ГОРЯЧИЕ ЗАКУСКИ",
    data: [
      {
        id: 1,
        image: "item-3.png",
        title: "Гусь",
        weight: "Вес: 225 г",
        description: "Фаршированный яблоками",
        price: "7 900 ₽",
      },
      {
        id: 2,
        image: "item-4.png",
        title: "Утка",
        weight: "Вес: 225 г",
        description: "Фаршированная рисом, курагой и айвой",
        price: "3 230 ₽",
      },
      {
        id: 3,
        image: "item-1.png",
        title: "Ягненок",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "620 ₽",
      },
      {
        id: 4,
        image: "item-2.png",
        title: "Индейка",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "450 ₽",
      },
      {
        id: 5,
        image: "item-3.png",
        title: "Гусь",
        weight: "Вес: 225 г",
        description: "Фаршированный яблоками",
        price: "7 900 ₽",
      },
      {
        id: 6,
        image: "item-4.png",
        title: "Утка",
        weight: "Вес: 225 г",
        description: "Фаршированная рисом, курагой и айвой",
        price: "3 230 ₽",
      },
    ],
  },
  {
    id: "meatDishes",
    title: "Мясные блюда",
    data: [
      {
        id: 1,
        image: "item-1.png",
        title: "Ягненок",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "620 ₽",
      },
      {
        id: 2,
        image: "item-2.png",
        title: "Индейка",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "450 ₽",
      },
      {
        id: 3,
        image: "item-3.png",
        title: "Гусь",
        weight: "Вес: 225 г",
        description: "Фаршированный яблоками",
        price: "7 900 ₽",
      },
      {
        id: 4,
        image: "item-4.png",
        title: "Утка",
        weight: "Вес: 225 г",
        description: "Фаршированная рисом, курагой и айвой",
        price: "3 230 ₽",
      },
      {
        id: 5,
        image: "item-1.png",
        title: "Ягненок",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "620 ₽",
      },
      {
        id: 6,
        image: "item-2.png",
        title: "Индейка",
        weight: "Вес: 225 г",
        description: "Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком",
        price: "450 ₽",
      },
    ],
  },
];

export default fakeDB;
